/**
 * TMDB API hooks — hand-written (not generated by Orval).
 * These call the Express backend, which proxies to TMDB using TMDB_API_KEY.
 *
 * The base URL for all requests is set via setBaseUrl() in main.tsx using
 * VITE_API_URL (the backend server root, e.g. https://your-api.render.com).
 * All paths here begin with /api/tmdb/... so the final URL is correct.
 */
import { useQuery } from "@tanstack/react-query";
import type { UseQueryOptions, UseQueryResult, QueryKey } from "@tanstack/react-query";
import { customFetch } from "./custom-fetch";
import type { ErrorType } from "./custom-fetch";

// ─── Utilities ───────────────────────────────────────────────────────────────

function buildQuery(params: Record<string, string | undefined>): string {
  const q = new URLSearchParams();
  for (const [k, v] of Object.entries(params)) {
    if (v !== undefined && v !== "") q.set(k, v);
  }
  const s = q.toString();
  return s ? `?${s}` : "";
}

// ─── Types ───────────────────────────────────────────────────────────────────

export interface TmdbMediaResult {
  id: number;
  title?: string;
  name?: string;
  poster_path?: string | null;
  backdrop_path?: string | null;
  vote_average?: number;
  release_date?: string;
  first_air_date?: string;
  media_type?: string;
  overview?: string;
}

export interface TmdbPagedResponse {
  results: TmdbMediaResult[];
  page: number;
  total_pages: number;
  total_results: number;
}

export interface TmdbGenre {
  id: number;
  name: string;
}

export interface TmdbGenresResponse {
  movie: TmdbGenre[];
  tv: TmdbGenre[];
}

// ─── Hooks ───────────────────────────────────────────────────────────────────

/** Trending movies, TV or all — defaults to "all" */
export function useGetTmdbTrending(
  params: { type?: string } = {},
  options?: { query?: Partial<UseQueryOptions<TmdbPagedResponse, ErrorType<unknown>>> },
): UseQueryResult<TmdbPagedResponse, ErrorType<unknown>> & { queryKey: QueryKey } {
  const type = params.type ?? "all";
  const queryKey: QueryKey = options?.query?.queryKey ?? ["tmdb", "trending", type];
  const result = useQuery<TmdbPagedResponse, ErrorType<unknown>>({
    queryKey,
    queryFn: () =>
      customFetch<TmdbPagedResponse>(`/api/tmdb/trending${buildQuery({ type })}`),
    ...options?.query,
  });
  return { ...result, queryKey };
}

export interface DiscoverParams {
  type: string;
  sort_by?: string;
  with_genres?: string;
  page?: string;
  with_watch_providers?: string;
  watch_region?: string;
}

/** Discover movies or TV shows with optional filters */
export function useGetTmdbDiscover(
  params: DiscoverParams,
  options?: { query?: Partial<UseQueryOptions<TmdbPagedResponse, ErrorType<unknown>>> },
): UseQueryResult<TmdbPagedResponse, ErrorType<unknown>> & { queryKey: QueryKey } {
  const { type, sort_by, with_genres, page, with_watch_providers, watch_region } = params;
  const queryKey: QueryKey = options?.query?.queryKey ?? ["tmdb", "discover", params];
  const result = useQuery<TmdbPagedResponse, ErrorType<unknown>>({
    queryKey,
    queryFn: () =>
      customFetch<TmdbPagedResponse>(
        `/api/tmdb/discover${buildQuery({ type, sort_by, with_genres, page, with_watch_providers, watch_region })}`,
      ),
    ...options?.query,
  });
  return { ...result, queryKey };
}

/** Anime content (animation + Japanese language) */
export function useGetTmdbAnime(
  params: { type?: "tv" | "movie"; page?: string } = {},
  options?: { query?: Partial<UseQueryOptions<TmdbPagedResponse, ErrorType<unknown>>> },
): UseQueryResult<TmdbPagedResponse, ErrorType<unknown>> & { queryKey: QueryKey } {
  const queryKey: QueryKey = options?.query?.queryKey ?? ["tmdb", "anime", params];
  const result = useQuery<TmdbPagedResponse, ErrorType<unknown>>({
    queryKey,
    queryFn: () =>
      customFetch<TmdbPagedResponse>(
        `/api/tmdb/anime${buildQuery({ type: params.type, page: params.page })}`,
      ),
    ...options?.query,
  });
  return { ...result, queryKey };
}

/** All movie and TV genres */
export function useGetTmdbGenres(
  options?: { query?: Partial<UseQueryOptions<TmdbGenresResponse, ErrorType<unknown>>> },
): UseQueryResult<TmdbGenresResponse, ErrorType<unknown>> & { queryKey: QueryKey } {
  const queryKey: QueryKey = options?.query?.queryKey ?? ["tmdb", "genres"];
  const result = useQuery<TmdbGenresResponse, ErrorType<unknown>>({
    queryKey,
    queryFn: () => customFetch<TmdbGenresResponse>(`/api/tmdb/genres`),
    ...options?.query,
  });
  return { ...result, queryKey };
}

/** Full details for a movie or TV show (credits, similar, recommendations, videos, reviews, images) */
export function useGetTmdbDetails(
  type: string,
  id: string,
  options?: { query?: Partial<UseQueryOptions<unknown, ErrorType<unknown>>> },
): UseQueryResult<unknown, ErrorType<unknown>> & { queryKey: QueryKey } {
  const queryKey: QueryKey = options?.query?.queryKey ?? ["tmdb", "details", type, id];
  const result = useQuery<unknown, ErrorType<unknown>>({
    queryKey,
    queryFn: () => customFetch(`/api/tmdb/details/${type}/${id}`),
    ...options?.query,
  });
  return { ...result, queryKey };
}

/** Episodes for a TV season */
export function useGetTmdbSeason(
  id: string,
  season: string,
  options?: { query?: Partial<UseQueryOptions<unknown, ErrorType<unknown>>> },
): UseQueryResult<unknown, ErrorType<unknown>> & { queryKey: QueryKey } {
  const queryKey: QueryKey = options?.query?.queryKey ?? ["tmdb", "season", id, season];
  const result = useQuery<unknown, ErrorType<unknown>>({
    queryKey,
    queryFn: () => customFetch(`/api/tmdb/season/${id}/${season}`),
    ...options?.query,
  });
  return { ...result, queryKey };
}

/** Streaming providers for a specific movie or TV show */
export function useGetTmdbWatchProviders(
  type: string,
  id: string,
  options?: { query?: Partial<UseQueryOptions<unknown, ErrorType<unknown>>> },
): UseQueryResult<unknown, ErrorType<unknown>> & { queryKey: QueryKey } {
  const queryKey: QueryKey = options?.query?.queryKey ?? ["tmdb", "watch-providers", type, id];
  const result = useQuery<unknown, ErrorType<unknown>>({
    queryKey,
    queryFn: () => customFetch(`/api/tmdb/watch-providers/${type}/${id}`),
    ...options?.query,
  });
  return { ...result, queryKey };
}

/** Multi-search (movies, TV, people) */
export function useGetTmdbSearch(
  params: { query: string },
  options?: { query?: Partial<UseQueryOptions<TmdbPagedResponse, ErrorType<unknown>>> },
): UseQueryResult<TmdbPagedResponse, ErrorType<unknown>> & { queryKey: QueryKey } {
  const queryKey: QueryKey = options?.query?.queryKey ?? ["tmdb", "search", params.query];
  const result = useQuery<TmdbPagedResponse, ErrorType<unknown>>({
    queryKey,
    queryFn: () =>
      customFetch<TmdbPagedResponse>(`/api/tmdb/search${buildQuery({ query: params.query })}`),
    ...options?.query,
  });
  return { ...result, queryKey };
}

/** Available streaming providers/platforms list */
export function useGetTmdbProviders(
  params: { watch_region?: string } = {},
  options?: { query?: Partial<UseQueryOptions<unknown, ErrorType<unknown>>> },
): UseQueryResult<unknown, ErrorType<unknown>> & { queryKey: QueryKey } {
  const queryKey: QueryKey = options?.query?.queryKey ?? ["tmdb", "providers", params.watch_region];
  const result = useQuery<unknown, ErrorType<unknown>>({
    queryKey,
    queryFn: () =>
      customFetch(`/api/tmdb/providers${buildQuery({ watch_region: params.watch_region })}`),
    ...options?.query,
  });
  return { ...result, queryKey };
}

/** Person details + combined credits */
export function useGetTmdbPerson(
  id: string,
  options?: { query?: Partial<UseQueryOptions<unknown, ErrorType<unknown>>> },
): UseQueryResult<unknown, ErrorType<unknown>> & { queryKey: QueryKey } {
  const queryKey: QueryKey = options?.query?.queryKey ?? ["tmdb", "person", id];
  const result = useQuery<unknown, ErrorType<unknown>>({
    queryKey,
    queryFn: () => customFetch(`/api/tmdb/person/${id}`),
    ...options?.query,
  });
  return { ...result, queryKey };
}

/** Movie collection */
export function useGetTmdbCollection(
  id: string,
  options?: { query?: Partial<UseQueryOptions<unknown, ErrorType<unknown>>> },
): UseQueryResult<unknown, ErrorType<unknown>> & { queryKey: QueryKey } {
  const queryKey: QueryKey = options?.query?.queryKey ?? ["tmdb", "collection", id];
  const result = useQuery<unknown, ErrorType<unknown>>({
    queryKey,
    queryFn: () => customFetch(`/api/tmdb/collection/${id}`),
    ...options?.query,
  });
  return { ...result, queryKey };
}
